

export const RESPONSE_MESSAGE = {
  SERVER_RUNNING: `myjobb.com server is up and running`,

  AUTH: {
    REGISTRATION_SUCCESS: "Registration successful",
    
    OTP: {
      SEND: "OTP Send",
      VERIFIED: "OTP Verified",
      INCORRECT: "Incorrect OTP",
      EXPIRED: "Expired OTP",
      NOT_FOUND: "OTP not found",
    },
    ONBOARDING_SUCCESS: "Onboarding completed successfully",
    INVALID_TOKEN: "Invalid Token",
    UNAUTHORIZED: "You are not authorized to access this resource.",
  },
  LIST: {
    COLLEGE: "College list fetched successfully",
    INDUSTRY: "Industry list fetched successfully",
    SKILL: "Skill list fetched successfully",
  },
  USER: {
    NOT_FOUND: "User not found!",
    PREFERED_LOCATION_INVALID : "User's prefered location not set or invalid",
    ALREADY_EXIST: "User already exist",
    EMAIL_USED: "This email address is already used.",
    UNAUTHORIZED: "User is unauthorized",
    FETCHED: "User fetched successfully",
    INVALID_ID: "Invalid User ID",
    UPDATED: "User updated successfully",
    SUB_ROLE: {
      NOT_FOUND: "Sub role not found",
      UPDATED: "Sub role updated successfully",
      INVALID: "Invalid sub role",
    },
    DELETED: "User deleted successfully",
    WORK_EXPERIENCE: {
      INVALID_DATA: "Invalid work experience data",
    },
    CERTIFICATE: {
      CREATED: "Certificate created successfully",
      FETCHED: "Certificate(s) fetched successfully",
      NOT_FOUND: "Certificate not found",
      DELETED: "Certificate deleted successfully",
      INVALID_DATA: "Invalid certificate data",
    },
    CURRENT_LOCATION_INVALID: "User's current location not set or invalid",
    PROFILE_UPDATED: "Profile is updated successfully",
    PROFILE_PROGRESS: {
      FETCHED: "Progress fetched successfully",
    },
    RESUME: {
      UPLOADED: "Resume uploaded successfully",
      MAX_LIMIT: "Only 3 resumes are allowed to be uploaded",
      FETCHED: "Resume(s) fetched successfully",
      NOT_FOUND: "Resume not found",
      DELETED: "Resume deleted successfully",
    },
    BOOKMARKS: {
      FETCHED: "Bookmarks fetched successfully",
      NOT_FOUND: "Bookmarks not found",
      ALREADY_EXIST: "Bookmark already exist",
      ADDED: "Bookmark added successfully",
      DELETED: "Bookmark deleted successfully",
    },
  },
  ORGANIZATION: {
    ALREADY_EXIST: "Organization already exist",
    REQUIRED: "User first need to create an organization.",
    ALREADY_PART_OF_ORGANIZATION: "User is already part of an organization.",
    CREATED: "Organization created successfully",
    UPDATED: "Organization updated successfully",
    DELETED: "Organization deleted successfully",
    NOT_FOUND: "Organization not found",
    LOGO_UPLOADED: "Logo uploaded successfully",
    FETCHED: "Organization fetched successfully",
    FETCHED_URI: "Organization uri fetched successfully",
    INVALID_ID: "Organization ID is invalid",
    MEDIA: {
      UPLOADED: "Media uploaded successfully",
      DELETED: "Media deleted successfully",
      NOT_FOUND: "Media not found",
      FETCHED: "Media fetched successfully",
      INVALID_ID: "Media ID is invalid",
    },
    STATS: {
      FETCHED: "Organization stats fetched successfully",
    },
  },
  JOB: {
    CREATED: "Job created successfully",
    NOT_FOUND: "Job not found",
    FETCHED: "Job(s) fetched successfully",
    NO_BOOKMARKS_FOUND:"No bookmarks found",
    INVALID_ID: "Job ID is invalid",
    SKILL_LIST_FETCHED: "Skill list fetched successfully",
    NO_ORGANIZATION: "Organization not found",
    INSUFFICIENT_PERCENTAGE:
      "You need to have at least 80% profile to create or apply for a job",
  },
  APPLICATION: {
    NOT_FOUND: "Application not found",
    INVALID_ID: "Application ID is invalid",
    NOT_ACCEPTED: "Application is not accepted",
    ACCEPTED: "Application accepted successfully",
    REJECTED: "Application rejected successfully",
    FETCHED: "Application(s) fetched successfully",
    SUBMITTED: "Application submitted successfully",
    ALREADY_APPLIED: "Application already applied",
    STATUS: {
      INVALID: "Invalid status request",
      CHANGED: "Application status changed successfully",
    },
    INVITE: {
      ALREADY_SENT: "Invite already sent",
      ALREADY_RECEIVED: "Invite already received",
      CREATED: "Invite created successfully",
      DELETED: "Invite deleted successfully",
      STATUS_CHANGED: "Invite status changed successfully",
      INVALID_EXCHANGE_TYPE: "Invalid exchange type",
      FETCHED_INVITES: "Invites fetched successfully",
      FETCHED_PENDING_COUNT: "Pending count fetched successfully",
      NOT_FOUND: "Invite not found",
    },
  },
  FILE: {
    NOT_FOUND: "File not found",
  },
  DOCUMENT: {
    UPLOADED: "Document uploaded successfully",
    INVALID_ID: "Document ID is invalid",
    FETCHED: "Document fetched successfully",
    NOT_FOUND: "Document not found",
    DELETED: "Document deleted successfully",
    UPDATED: "Document updated successfully",
    NO_FILE: "No file found",
  },
  SUPPORT: {
    CREATED: "Support request created successfully",
    FETCHED: "Support requests fetched successfully",
    NOT_FOUND: "Support request not found",
    ALREADY_RAISED: "Support request already raised",
  },
  REPORT_BUG: {
    CREATED: "Bug reported successfully",
    FETCHED: "Bugs fetched successfully",
    NOT_FOUND: "Bug not found",
    INVALID: "Invalid bug type",
    INCOMPLETE: "Incomplete details",
  },
  FEEDBACK: {
    SUBMITTED: "Feedback submitted successfully",
  },
  NOTIFICATION: {
    INVALID_DATA: "Invalid notification data",
    SENT: "Notification sent successfully",
    ERROR: "Error sending notification",
  },
} as const;
